### ISSUE TITLE
Request Aborted when parsing

### ISSUE THREAD

**Issue by ChenyaZhang** [expressjs/node-multiparty#147]
Everything get called but at last there is an error "request aborted":

```js
var multiparty = require('multiparty');
var http = require('http');
var util = require('util');

http.createServer(function(req, res) {

  if (req.url === '/upload' && req.method === 'POST') {
    // parse a file upload
    var count = 0;
    var form = new multiparty.Form();

    console.log('This is called 1!');

    // Errors may be emitted 
    // Note that if you are listening to 'part' events, the same error may be 
    // emitted from the `form` and the `part`. 
    form.on('error', function(err) {
      console.log('Error parsing form: ' + err.stack);
    });
    
    // form.on('file', function(err, files) {
    //   console.log('files: %@', files);
    //   count++;
    // });

    // Parts are emitted when parsing the form 
    form.on('part', function(part) {
      // You *must* act on the part by reading it 
      // NOTE: if you want to ignore it, just call "part.resume()" 

      console.log('This is called 2!');
     
      if (!part.filename) {
        // filename is not defined when this is a field and not a file 
        console.log('got field named ' + part.name);
        // ignore field's content 
        part.resume();
      }
     
      if (part.filename) {
        // filename is defined when this is a file 
        count++;
        console.log('got file named ' + part.name);
        // ignore file's content here 
        console.log('Byte Offset: ' + part.byteOffset);
        part.resume();
      }
     
      part.on('error', function(err) {
        console.log('error here!');
      });
    });
     
    // Close emitted after form parsed 
    form.on('close', function() {
      console.log('Upload completed!');
      // res.setHeader('text/plain');
      // res.end('Received ' + count + ' files');
      console.log('Received ' + count + ' files');
    });

    form.parse(req);
    // form.parse(req, function(err, fields, files) {
    //   res.writeHead(200, {'content-type': 'text/plain'});
    //   res.write('received upload:\n\n');
    //   res.end(util.inspect({fields: fields, files: files}));
    //   // console.log('fields: %@', fields);
    //   // console.log('files: %@', files);
    // });
  }

}).listen(8080);
```

In my console:
(Debug msgs all printed)

```
Error parsing form: Error: Request aborted
    at IncomingMessage.onReqAborted (/Users/Melinda/Desktop/test/node_modules/multiparty/index.js:183:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.socketOnEnd (_http_server.js:431:7)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I was told not to use any callback in form.parse() in a previous post. But it seems like there is an error when parsing?

**Comment by dougwilson** [comment]
That error has nothing to do with not using a callback, it means your request was aborted by the client. That is an error, and of course the client can abort at any time, even after you read parts of the request.
