### ISSUE TITLE
request aborted when using only fields

### ISSUE THREAD

**Issue by arisAlexis** [expressjs/node-multiparty#154]
the below code emits 

>  at IncomingMessage.onReqAborted (/home/webapp/therecord_server/node_modules/multiparty/index.js:183:17)
api-0 (err):     at emitNone (events.js:86:13)
api-0 (err):     at IncomingMessage.emit (events.js:185:7)

with the following code and a valid email:

```javascript
return new Promise(resolve => {
    let parsedObject = {};
    let form = new multiparty.Form({ autoFields: true, autoFiles: false });

        form.on('error', function(err) {
          console.log('Error parsing form: ' + err.stack);
        });

        form.on('field', function(field, value) {          
          switch (field) {
            case 'sender': parsedObject.from = value; break;
            case 'recipient': parsedObject.to = value; break;
            case 'subject': parsedObject.subject = value; break;
            case 'body-plain': parsedObject.body = value; break;
          }
        });

        form.on('abort',() => resolve(parsedObject));
        form.on('close',() => resolve(parsedObject));
        
        form.parse(req);
  });
```

Note that I don't care about the attachments at all.

**Comment by dougwilson** [comment]
Hi @arisAlexis with the current feature set, you have to add a `part` listener to handle that. Add the following:
```js
form.on('part', function (part) {
  if (part.filename) part.resume()
})
```
